CREATE TABLE document
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_created TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    txt         OID,
    CONSTRAINT pk_document PRIMARY KEY (id)
);